version: 0.2

phases:
  install:
    commands:
      - echo "Release 1.0.1"
      - pwd
      - ls -alrt
      - . ./operations/codebuild-extras.sh 2>/dev/null
      - echo "Build branch ${CODEBUILD_GIT_BRANCH}"
      - echo "Safe branch  ${CODEBUILD_GIT_CLEAN_BRANCH}"
      - echo "__________ Building $application __________"
  build:
    commands:
      - npm install
      - cd generators/app/templates
      - npm install
      - npm run build
      - cd ../../../
      - cp -rvf generators/app/templates/build ./
  post_build:
    commands:
      - echo "No explicit post build commands yet..."
artifacts:
  files:
    - build/**/*
  name: inrupt-generator-solid-react-${CODEBUILD_GIT_CLEAN_BRANCH}-$(date +%Y-%m-%d_%H-%M-%S).zip

